version: '3'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: ${INTEGRATION_TEST_TIMEOUT}

  phoned:
    image: wazo-dird-phoned-test
    ports:
      - "9498"
      - "9499"
    volumes:
      - "../..:/usr/src/wazo-dird-phoned"
      - "./ssl:/etc/ssl"
      - "./auth_keys:/tmp/auth_keys"
      - "./etc/wazo-dird-phoned/conf.d/50-auth.yml:/etc/wazo-dird-phoned/conf.d/50-auth.yml"
      - "./etc/wazo-dird-phoned/conf.d/50-dird.yml:/etc/wazo-dird-phoned/conf.d/50-dird.yml"
      - "./etc/wazo-dird-phoned/conf.d/50-rest-api.yml:/etc/wazo-dird-phoned/conf.d/50-rest-api.yml"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python3.5/site-packages/xivo"

  dird:
    image: p0bailey/docker-flask
    expose:
      - "9489"
    volumes:
      - "./dird_data:/tmp"
      - "./ssl:/etc/ssl"
    command: "python /tmp/mock-wazo-dird.py 9489"

  auth:
    image: p0bailey/docker-flask
    expose:
      - "9497"
    volumes:
      - "./auth_data:/tmp"
      - "./ssl:/etc/ssl"
    command: "python /tmp/mock-wazo-auth.py 9497"
